# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# Use static linking for Capacitor 8.x to avoid "Multiple commands produce" errors
use_frameworks! :linkage => :static

target 'App' do
  # Capacitor
  pod 'Capacitor', '~> 8.0'
  pod 'CapacitorCordova', '~> 8.0'

  # Add your native plugins here
  # pod '@capacitor/push-notifications', :path => '../../node_modules/@capacitor/push-notifications'
  # pod '@capacitor/local-notifications', :path => '../../node_modules/@capacitor/local-notifications'
  # pod '@capacitor/app', :path => '../../node_modules/@capacitor/app'
  # pod '@capacitor/haptics', :path => '../../node_modules/@capacitor/haptics'
  # pod '@capacitor/keyboard', :path => '../../node_modules/@capacitor/keyboard'
  # pod '@capacitor/device', :path => '../../node_modules/@capacitor/device'
  # pod '@capacitor/preferences', :path => '../../node_modules/@capacitor/preferences'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Fix for "Multiple commands produce" error
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end

  # Fix duplicate framework embedding issue
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_SOURCE_FILE_NAMES"] = "*.h"
  end
end
